// Generated by scripts/generate-env-reference.mjs (npm run miner:env-reference). Do not edit manually.
export type MinerEnvReferenceRow = {
  name: string;
  firstReference: string;
  defaultValue: string | null;
};

export const AMS_ENV_REFERENCE_ROWS: MinerEnvReferenceRow[] = [
  {
    name: "LOOPOVER_MINER_AMS_COLLECTOR_TOKEN",
    firstReference: "lib/orb-export.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_COLLECTOR_URL",
    firstReference: "lib/orb-export.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_OAUTH_CLIENT_ID",
    firstReference: "lib/oauth-device-flow.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_POLICY_PATH",
    firstReference: "lib/ams-policy.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_ATTEMPT_LOG_DB",
    firstReference: "lib/attempt-log.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_CLAIM_LEDGER_DB",
    firstReference: "lib/claim-ledger.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_CONFIG_DIR",
    firstReference: "lib/laptop-init.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_CONTRIBUTION_PROFILE_CACHE_DB",
    firstReference: "lib/contribution-profile-cache.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_CONTROL_PLANE",
    firstReference: "lib/tenant-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_CONTROL_PLANE_ADMIN_TOKEN",
    firstReference: "lib/tenant-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_CONTROL_PLANE_URL",
    firstReference: "lib/tenant-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_DENY_HOOK_SYNTHESIS_DB",
    firstReference: "lib/deny-hook-synthesis.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_DISABLE_EGRESS_FIREWALL",
    firstReference: "lib/generate-egress-firewall-config.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_DISCOVERY_INDEX_URL",
    firstReference: "lib/discovery-index-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_DISCOVERY_PLANE",
    firstReference: "lib/discovery-index-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_DISCOVERY_SHARED_SECRET",
    firstReference: "lib/discovery-index-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_DISCOVERY_TELEMETRY",
    firstReference: "lib/discovery-index-client.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_EVENT_LEDGER_DB",
    firstReference: "lib/event-ledger.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_GOVERNOR_LEDGER_DB",
    firstReference: "lib/governor-ledger.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_GOVERNOR_STATE_DB",
    firstReference: "lib/governor-state.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_LAPTOP_STATE_DB",
    firstReference: "lib/laptop-init.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_LOG_LEVEL",
    firstReference: "lib/logger.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_NEON_API_KEY",
    firstReference: "lib/egress-allowlist.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_NEON_PARENT_BRANCH_ID",
    firstReference: "lib/egress-allowlist.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_NEON_PROJECT_ID",
    firstReference: "lib/egress-allowlist.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_NO_UPDATE_CHECK",
    firstReference: "lib/update-check.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_ORB_EXPORT_DB",
    firstReference: "lib/orb-export.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_PLAN_STORE_DB",
    firstReference: "lib/plan-store.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_POLICY_DOC_CACHE_DB",
    firstReference: "lib/policy-doc-cache.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_POLICY_VERDICT_CACHE_DB",
    firstReference: "lib/policy-verdict-cache.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_PORTFOLIO_QUEUE_DB",
    firstReference: "lib/portfolio-queue.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_PREDICTION_LEDGER_DB",
    firstReference: "lib/prediction-ledger.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_RANKED_CANDIDATES_DB",
    firstReference: "lib/ranked-candidates.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_REPLAY_SNAPSHOT_DB",
    firstReference: "lib/replay-snapshot.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_RUN_STATE_DB",
    firstReference: "lib/run-state.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_SENTRY_DSN",
    firstReference: "lib/egress-allowlist.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_SENTRY_ENVIRONMENT",
    firstReference: "lib/sentry.ts",
    defaultValue: "production",
  },
  {
    name: "LOOPOVER_MINER_VERSION",
    firstReference: "lib/version.ts",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_WORKTREE_ALLOCATOR_DB",
    firstReference: "lib/worktree-allocator.ts",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_WORKTREE_DIR",
    firstReference: "lib/worktree-allocator.ts",
    defaultValue: "",
  },
  {
    name: "MINER_CODING_AGENT_CLAUDE_MODEL",
    firstReference: "packages/loopover-engine/src/miner/driver-factory.ts",
    defaultValue: null,
  },
  {
    name: "MINER_CODING_AGENT_CODEX_MODEL",
    firstReference: "packages/loopover-engine/src/miner/driver-factory.ts",
    defaultValue: null,
  },
  {
    name: "MINER_CODING_AGENT_PAUSED",
    firstReference: "packages/loopover-engine/src/miner/coding-agent-mode.ts",
    defaultValue: "",
  },
  {
    name: "MINER_CODING_AGENT_PROVIDER",
    firstReference: "lib/laptop-init.ts",
    defaultValue: "",
  },
  {
    name: "MINER_CODING_AGENT_TIMEOUT_MS",
    firstReference: "packages/loopover-engine/src/miner/driver-factory.ts",
    defaultValue: null,
  },
];

export const AMS_ENV_REFERENCE_MARKDOWN = [
  "# loopover-miner environment variable reference",
  "",
  "Generated by `npm run miner:env-reference`. Do not edit manually.",
  "",
  "| Name | First reference | Default |",
  "| --- | --- | --- |",
  '| `LOOPOVER_MINER_AMS_COLLECTOR_TOKEN` | `lib/orb-export.ts` | `""` |',
  '| `LOOPOVER_MINER_AMS_COLLECTOR_URL` | `lib/orb-export.ts` | `""` |',
  '| `LOOPOVER_MINER_AMS_OAUTH_CLIENT_ID` | `lib/oauth-device-flow.ts` | `""` |',
  "| `LOOPOVER_MINER_AMS_POLICY_PATH` | `lib/ams-policy.ts` | (none) |",
  "| `LOOPOVER_MINER_ATTEMPT_LOG_DB` | `lib/attempt-log.ts` | (none) |",
  "| `LOOPOVER_MINER_CLAIM_LEDGER_DB` | `lib/claim-ledger.ts` | (none) |",
  '| `LOOPOVER_MINER_CONFIG_DIR` | `lib/laptop-init.ts` | `""` |',
  "| `LOOPOVER_MINER_CONTRIBUTION_PROFILE_CACHE_DB` | `lib/contribution-profile-cache.ts` | (none) |",
  '| `LOOPOVER_MINER_CONTROL_PLANE` | `lib/tenant-client.ts` | `""` |',
  '| `LOOPOVER_MINER_CONTROL_PLANE_ADMIN_TOKEN` | `lib/tenant-client.ts` | `""` |',
  '| `LOOPOVER_MINER_CONTROL_PLANE_URL` | `lib/tenant-client.ts` | `""` |',
  "| `LOOPOVER_MINER_DENY_HOOK_SYNTHESIS_DB` | `lib/deny-hook-synthesis.ts` | (none) |",
  "| `LOOPOVER_MINER_DISABLE_EGRESS_FIREWALL` | `lib/generate-egress-firewall-config.ts` | (none) |",
  '| `LOOPOVER_MINER_DISCOVERY_INDEX_URL` | `lib/discovery-index-client.ts` | `""` |',
  '| `LOOPOVER_MINER_DISCOVERY_PLANE` | `lib/discovery-index-client.ts` | `""` |',
  '| `LOOPOVER_MINER_DISCOVERY_SHARED_SECRET` | `lib/discovery-index-client.ts` | `""` |',
  '| `LOOPOVER_MINER_DISCOVERY_TELEMETRY` | `lib/discovery-index-client.ts` | `""` |',
  "| `LOOPOVER_MINER_EVENT_LEDGER_DB` | `lib/event-ledger.ts` | (none) |",
  "| `LOOPOVER_MINER_GOVERNOR_LEDGER_DB` | `lib/governor-ledger.ts` | (none) |",
  "| `LOOPOVER_MINER_GOVERNOR_STATE_DB` | `lib/governor-state.ts` | (none) |",
  "| `LOOPOVER_MINER_LAPTOP_STATE_DB` | `lib/laptop-init.ts` | (none) |",
  '| `LOOPOVER_MINER_LOG_LEVEL` | `lib/logger.ts` | `""` |',
  "| `LOOPOVER_MINER_NEON_API_KEY` | `lib/egress-allowlist.ts` | (none) |",
  "| `LOOPOVER_MINER_NEON_PARENT_BRANCH_ID` | `lib/egress-allowlist.ts` | (none) |",
  "| `LOOPOVER_MINER_NEON_PROJECT_ID` | `lib/egress-allowlist.ts` | (none) |",
  '| `LOOPOVER_MINER_NO_UPDATE_CHECK` | `lib/update-check.ts` | `""` |',
  "| `LOOPOVER_MINER_ORB_EXPORT_DB` | `lib/orb-export.ts` | (none) |",
  "| `LOOPOVER_MINER_PLAN_STORE_DB` | `lib/plan-store.ts` | (none) |",
  "| `LOOPOVER_MINER_POLICY_DOC_CACHE_DB` | `lib/policy-doc-cache.ts` | (none) |",
  "| `LOOPOVER_MINER_POLICY_VERDICT_CACHE_DB` | `lib/policy-verdict-cache.ts` | (none) |",
  "| `LOOPOVER_MINER_PORTFOLIO_QUEUE_DB` | `lib/portfolio-queue.ts` | (none) |",
  "| `LOOPOVER_MINER_PREDICTION_LEDGER_DB` | `lib/prediction-ledger.ts` | (none) |",
  "| `LOOPOVER_MINER_RANKED_CANDIDATES_DB` | `lib/ranked-candidates.ts` | (none) |",
  "| `LOOPOVER_MINER_REPLAY_SNAPSHOT_DB` | `lib/replay-snapshot.ts` | (none) |",
  "| `LOOPOVER_MINER_RUN_STATE_DB` | `lib/run-state.ts` | (none) |",
  "| `LOOPOVER_MINER_SENTRY_DSN` | `lib/egress-allowlist.ts` | (none) |",
  '| `LOOPOVER_MINER_SENTRY_ENVIRONMENT` | `lib/sentry.ts` | `"production"` |',
  '| `LOOPOVER_MINER_VERSION` | `lib/version.ts` | `""` |',
  "| `LOOPOVER_MINER_WORKTREE_ALLOCATOR_DB` | `lib/worktree-allocator.ts` | (none) |",
  '| `LOOPOVER_MINER_WORKTREE_DIR` | `lib/worktree-allocator.ts` | `""` |',
  "| `MINER_CODING_AGENT_CLAUDE_MODEL` | `packages/loopover-engine/src/miner/driver-factory.ts` | (none) |",
  "| `MINER_CODING_AGENT_CODEX_MODEL` | `packages/loopover-engine/src/miner/driver-factory.ts` | (none) |",
  '| `MINER_CODING_AGENT_PAUSED` | `packages/loopover-engine/src/miner/coding-agent-mode.ts` | `""` |',
  '| `MINER_CODING_AGENT_PROVIDER` | `lib/laptop-init.ts` | `""` |',
  "| `MINER_CODING_AGENT_TIMEOUT_MS` | `packages/loopover-engine/src/miner/driver-factory.ts` | (none) |",
  "",
].join("\n");
